/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/log-in": {
    post: operations["AuthController_logIn"];
  };
  "/api/v1/auth/sign-up": {
    post: operations["AuthController_signUp"];
  };
  "/api/v1/auth/refresh": {
    post: operations["AuthController_refresh"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LogInRequest: {
      email: string;
      password: string;
    };
    LogInResponse: {
      accessToken: string;
      refreshToken: string;
    };
    SignUpRequest: {
      email: string;
      firstName: string;
      lastName: string;
      password: string;
    };
    SignUpResponse: {
      accessToken: string;
      refreshToken: string;
    };
    RefreshResponse: {
      accessToken: string;
      refreshToken: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuthController_logIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogInRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["LogInResponse"];
        };
      };
    };
  };
  AuthController_signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["SignUpResponse"];
        };
      };
    };
  };
  AuthController_refresh: {
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RefreshResponse"];
        };
      };
    };
  };
}
