/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/log-in": {
    /** The Refresh Token is stored in browser cookies */
    post: operations["AuthController_logIn"];
  };
  "/api/v1/auth/sign-up": {
    /** The Refresh Token is stored in browser cookies */
    post: operations["AuthController_signUp"];
  };
  "/api/v1/auth/refresh": {
    /** The Refresh Token is stored in browser cookies */
    post: operations["AuthController_refresh"];
  };
  "/api/v1/auth/access-token/check": {
    get: operations["AuthController_checkAccessToken"];
  };
  "/api/v1/auth/log-out": {
    /** The Refresh Token is deleted from browser cookies */
    post: operations["AuthController_logOut"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LogInRequest: {
      email: string;
      password: string;
    };
    AuthorizedUser: {
      /** @enum {string} */
      role: "USER" | "ADMIN";
      id: number;
      email: string;
      firstName: string;
      lastName: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LogInResponse: {
      accessToken: string;
      user: components["schemas"]["AuthorizedUser"];
    };
    SignUpRequest: {
      email: string;
      firstName: string;
      lastName: string;
      password: string;
    };
    SignUpResponse: {
      accessToken: string;
      user: components["schemas"]["AuthorizedUser"];
    };
    RefreshResponse: {
      accessToken: string;
      user: components["schemas"]["AuthorizedUser"];
    };
    CheckAccessTokenResponse: {
      /** @enum {string} */
      role: "USER" | "ADMIN";
      id: number;
      email: string;
      firstName: string;
      lastName: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** The Refresh Token is stored in browser cookies */
  AuthController_logIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogInRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["LogInResponse"];
        };
      };
    };
  };
  /** The Refresh Token is stored in browser cookies */
  AuthController_signUp: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["SignUpResponse"];
        };
      };
    };
  };
  /** The Refresh Token is stored in browser cookies */
  AuthController_refresh: {
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RefreshResponse"];
        };
      };
    };
  };
  AuthController_checkAccessToken: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CheckAccessTokenResponse"];
        };
      };
    };
  };
  /** The Refresh Token is deleted from browser cookies */
  AuthController_logOut: {
    responses: {
      201: {
        content: never;
      };
    };
  };
}
